news_sites:
  eluniversal:
    url: http://www.eluniversal.com.mx
    queries:
      homepage_articles_links: ".field-content a"
      article_body: ".field-name-body"
      article_title: ".pane-content h1"
  eltiempo:
    url: https://www.eltiempo.com/
    queries:
      homepage_articles_links: ".title-container a"
      article_body: ".articulo-contenido .modulos"
      article_title: ".titulo-principal-bk h1"
